version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - staticcheck
    - govet
    - ineffassign
    - unconvert
    - unparam
    - unused
    - whitespace
    - gocognit
    - prealloc

  settings:
    govet:
      enable:
        - shadow
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 2
      min-occurrences: 4
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - unnamedResult
    funlen:
      lines: 100
      statements: 50

formatters:
  default: none
  enable:
    - gofmt
    - goimports
